local component = require("component")
local term = require("term")
gpu = component.gpu

fg_standart = component.gpu.getForeground()
bg_standart = component.gpu.getBackground()

function UI_Build()
    term.clear()
    gpu.setResolution(160,40)
    gpu.setForeground(0x00FFFF)
    term.setCursor(1,1)
    print("╭───────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮")
    print("│                       │                                                                                                                                      │")
    print("├───────────────────────╯                                                                                                                                      │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯")
    term.setCursor(2,2)
    gpu.setForeground(fg_standart)
    print(header.." v"..version)
    end