local component = require("component")
local term = require("term")
gpu = component.gpu

fg_standart = component.gpu.getForeground()
bg_standart = component.gpu.getBackground()

function UI_Build()
    term.clear()
    gpu.setResolution(160,40)
    gpu.setForeground(0x00FFFF)
    term.setCursor(1,1)
    print("╭───────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮")
    print("│                       │                                                                                                                                      │")
    print("├───────────────────────╯                                                                                                                                      │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("│      ╭────────────╮      ╭────────────╮                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      │            │      │            │                                                                                                                      │")
    print("│      ╰────────────╯      ╰────────────╯                                                                                                                      │")
    print("│                                                                                                                                                              │")
    print("│                                                                                                                                                              │")
    print("╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯")
    term.setCursor(2,2)
    gpu.setForeground(fg_standart)
    print(header.." v"..version)
    end

function reactor_status(status_1, status_2)
 --gpu.fill(Spalte, Zeile, Dicke nach rechts, Höhe, "█")
    --reactor 1
    gpu.fill(115, 3, 12, 6, "█")
    term.setCursor(116,4)
    print("Reactor  1")
    --reactor 2
    gpu.fill(130, 3, 12, 6, "█")
    term.setCursor(131,4)
    print("Reactor  2")
end

function bar_water(tank_water_bar)
    --gpu.fill(Spalte, Zeile, Dicke nach rechts, Höhe, "█")
    component.gpu.setForeground(0x00CD00)
    gpu.fill(8, 36, 12, tank_water_bar, "█")
    component.gpu.setForeground(0xCD0000)
    gpu.fill(8, tank_water_bar+36, 12, 31-tank_water_bar, "█")
    component.gpu.setForeground(fg_standart)
   end